# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# Enhanced by Secure Chat API team

name: Build and deploy Node.js app to Azure Web App - SafeChatAi

on:
  push:
    branches:
      - main
    paths:
      - 'backend/nodejs-service/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend/nodejs-service
    permissions:
      contents: read
      actions: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js version
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'
          cache-dependency-path: './backend/nodejs-service/package-lock.json'

      - name: Install dependencies
        run: npm ci

      - name: Build application
        run: npm run build

      - name: Run tests
        run: npm run test:ci

      - name: Prepare deployment files
        run: |
          # Copy necessary files for deployment
          cp package.json dist/
          cp package-lock.json dist/
          cp web.config dist/

      - name: Create deployment package
        run: |
          cd dist
          zip -r ../release.zip . -x "*.map"

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_AA2EE23B1BDD434596BA38A337AAEDD9 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_AF8C577CA1C04456BE42AA6552A05341 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_05D2F6491DF14DA7898614DAB3E07761 }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'SafeChatAi'
          slot-name: 'Production'
          package: .

      - name: ✅ Deployment Summary
        run: |
          echo "🎉 Deployment completed successfully!"
          echo "🌐 App URL: https://safechatai.azurewebsites.net"
          echo "📡 Socket.io URL: https://safechatai.azurewebsites.net"
          echo "🔍 Health Check: https://safechatai.azurewebsites.net/health"
